version: "3.1"
services:
    mietaro_web:
        build:
            context: ./docker/PHP
            dockerfile: Dockerfile
        container_name: "mietaro_web"
        image: "centos:7.5.1804"
        restart: always
        networks:
            mietaroNet:
                ipv4_address: 172.10.0.5
        volumes: 
            - ./source:/var/www/html/mietaro
            - ./docker/log:/var/log
        stdin_open: true
        tty: true
        ports:
            - "30080:80"
    mietaro_db:
        build:
            context: ./docker/MySQL
            dockerfile: Dockerfile
        image: "mysql:5.7"
        container_name: "mietaro_db"
        restart: always

        environment: 
            MYSQL_DABASE: mietaro
            MYSQL_USER: user
            MYSQL_PASSWORD: ecomira
            MYSQL_ROOT_PASSWORD: ecomira
            TZ: Asia/Tokyo

        networks:
            mietaroNet:
                ipv4_address: 172.10.0.6
        volumes:
            # - ./docker/db/mysql/tool:/tool
            - ./docker/db/mysql/conf.d:/etc/mysql/conf.d
            # - ./docker/db/mysql/data:/var/lib/mysql
            - ./docker/db/mysql/log:/var/log/mysql
            - ./docker/db/mysql/mysql-files:/var/lib/mysql-files

        ports:
            - "3306:3306"

networks:
    mietaroNet:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.10.0.0/24