# ###########################################################
# 
# 作成日 2019/12/08     作成者 akihiro.toda
# 更新日 2020/02/17     更新者 akihiro.toda
# 
# Copyright (c) Flugel System Studio - All rights reserved.
# ###########################################################
version: "3.7"
services:
    # PHP-apache
    web:
        build: ./PHP-apache
        container_name: mietaro_web
        restart: always
        networks:
            mietaroNet:
                ipv4_address: 172.10.0.5
        volumes: 
            - ./source:/var/www/html/mietaro
            - ./PHP-apache/log:/var/log
        # stdin_open: true
        # tty: true
        ports:
            - "30080:80"

    # MySQL
    # db:
    #     build: ./MySQL
    #     contailner_name: mietaro_db
    #     restart: always
    #     netwokrs:
    #         mietaroNet:
    #             ipv4_address: 172.10.0.6
    #     volimes:
    #         - ./MySQL/data/:/var/lib/MySQL
    #         - ./MySQL/sql/:/docker-entrypoint-initdb.d
    #     ports:
    #         - "3306:3306"

networks:
    mietaroNet:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.10.0.0/24